// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDylnN2ONQw6SWM38zbPJWn6fkd4G32phg',
    appId: '1:693612482237:android:bdf814a21f56d01d5db1d4',
    messagingSenderId: '693612482237',
    projectId: 'toki-57d35',
    storageBucket: 'toki-57d35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDylnN2ONQw6SWM38zbPJWn6fkd4G32phg',
    appId: '1:693612482237:ios:bdf814a21f56d01d5db1d4',
    messagingSenderId: '693612482237',
    projectId: 'toki-57d35',
    storageBucket: 'toki-57d35.firebasestorage.app',
    iosBundleId: 'com.toki.ios',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDylnN2ONQw6SWM38zbPJWn6fkd4G32phg',
    appId: '1:693612482237:web:bdf814a21f56d01d5db1d4',
    messagingSenderId: '693612482237',
    projectId: 'toki-57d35',
    authDomain: 'toki-57d35.firebaseapp.com',
    storageBucket: 'toki-57d35.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDylnN2ONQw6SWM38zbPJWn6fkd4G32phg',
    appId: '1:693612482237:ios:bdf814a21f56d01d5db1d4',
    messagingSenderId: '693612482237',
    projectId: 'toki-57d35',
    storageBucket: 'toki-57d35.firebasestorage.app',
    iosBundleId: 'com.toki.ios',
  );
}
